"""Layer 4 — Cell Matrix package (4-dim P0 + parent3/parent2 + shadow context).

Spec source: vault/30_components/layer-4-cell-matrix.md.
"""

from polaris.core.cell_matrix.routing import (
    Quartile,
    classify_quartile,
    compute_routing_mult,
    fetch_cell_stat,
    fetch_parent2_score,
    fetch_parent3_score,
    fetch_posterior_tilt,
    load_eligible_scores,
    load_eligible_scores_decayed,
    resolve_routing_for_cell,
    update_on_trade_close,
)
from polaris.core.cell_matrix.schema import (
    CELL_BASELINE_N,
    CELL_DECAY_HALF_LIFE_SEC,
    CELL_MIN_LIVE_N,
    CELL_MIN_POOL_SIZE,
    CELL_SHRINKAGE_N,
    EIGHT_DIM_PROMOTION_THRESHOLD,
    ROUTING_BOTTOM_MULT,
    ROUTING_MID_MULT,
    ROUTING_TOP_MULT,
    CellContext,
    CellKeyP0,
    CellStat,
    TradeClose,
)
from polaris.core.cell_matrix.score import (
    POSTERIOR_TILT_CEIL,
    POSTERIOR_TILT_FLOOR,
    POSTERIOR_TILT_MIN_N,
    REGIME_ALIGN_AMPLIFY,
    REGIME_ALIGN_DAMPEN,
    REGIME_ALIGN_NEUTRAL,
    apply_regime_alignment,
    compute_avg_pnl_r,
    compute_cell_score,
    decay_factor,
    posterior_tilt,
    regime_alignment_mult,
    resolve_effective_score,
)

__all__ = [
    "CELL_BASELINE_N",
    "CELL_DECAY_HALF_LIFE_SEC",
    "CELL_MIN_LIVE_N",
    "CELL_MIN_POOL_SIZE",
    "CELL_SHRINKAGE_N",
    "EIGHT_DIM_PROMOTION_THRESHOLD",
    "POSTERIOR_TILT_CEIL",
    "POSTERIOR_TILT_FLOOR",
    "POSTERIOR_TILT_MIN_N",
    "REGIME_ALIGN_AMPLIFY",
    "REGIME_ALIGN_DAMPEN",
    "REGIME_ALIGN_NEUTRAL",
    "ROUTING_BOTTOM_MULT",
    "ROUTING_MID_MULT",
    "ROUTING_TOP_MULT",
    "CellContext",
    "CellKeyP0",
    "CellStat",
    "Quartile",
    "TradeClose",
    "apply_regime_alignment",
    "classify_quartile",
    "compute_avg_pnl_r",
    "compute_cell_score",
    "compute_routing_mult",
    "decay_factor",
    "fetch_cell_stat",
    "fetch_parent2_score",
    "fetch_parent3_score",
    "fetch_posterior_tilt",
    "load_eligible_scores",
    "load_eligible_scores_decayed",
    "posterior_tilt",
    "regime_alignment_mult",
    "resolve_effective_score",
    "resolve_routing_for_cell",
    "update_on_trade_close",
]
